apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: querygray
    version: v2
  name: query-gray
  namespace: plane-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: querygray
  template:
    metadata:
      labels:
        app: querygray
        version: v2
    spec:
      containers:
      - image: hnkjzyxy.com/library/plane-queryGray-service:v1.0
        name: querygray
        ports:
        - containerPort: 8088
# Probe set
        readinessProbe:
          httpGet:
            port: 8088
            path: /query/health
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            port: 8088
            path: /query/health
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
# Prestop set
        lifecycle:
          preStop:
            exec:
              command:
              - "curl"
              - "-X"
              - "POST"
              - "http://localhost:8088/query/shutdown"

# Qos set
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
# Volume Set
        volumeMounts:
         - name: time
           mountPath: /etc/localtime
      volumes:
       - name: time
         hostPath:
           path: /etc/localtime
# Node Set
#      nodeSelector:
#       kubernetes.io/hostname: k8s-master-node1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: querygray
  name: query-gray
  namespace: plane-platform
spec:
  ports:
  - name: http-query
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: querygray
  type: ClusterIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
