apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: query
    version: v1
  name: query
  namespace: plane-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
        version: v1
    spec:
      containers:
      - image: hnkjzyxy.com/library/plane-query-service:v1.0
        name: query
        ports:
        - containerPort: 8081
# Probe set
        readinessProbe:
          httpGet:
            port: 8081
            path: /query/health
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            port: 8081
            path: /query/health
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
# Prestop set
        lifecycle:
          preStop:
            exec:
              command:
              - "curl"
              - "-X"
              - "POST"
              - "http://localhost:8081/query/shutdown"

# Qos set
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
# Volume Set
        volumeMounts:
         - name: time
           mountPath: /etc/localtime
      volumes:
       - name: time
         hostPath:
           path: /etc/localtime
# Node Set
#      nodeSelector:
#       kubernetes.io/hostname: k8s-master-node1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: query
  name: query
  namespace: plane-platform
spec:
  ports:
  - name: http-query
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: query
  type: ClusterIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
